### ISSUE TITLE
Coldcache duplicating content in Preview

### ISSUE THREAD

**Issue by mzlock** [pixelandtonic/ColdCache#1]
The relevant parts of my template:

```
{% block content %}
  {% cache for 1 hour %}
    Main content - light caching
  {% endcache %}

  {% coldcache for 1 week %}
    Related content - coldcache and change infrequently
  {% endcoldcache %}

{% endblock %}
```

In Preview mode (either Live Preview or the Preview link w/ a token), the content from the first cache tag is duplicated in the second. So, only in Preview, I get:

```
Main content

Main content
```

Instead of:

```
Main content

Related content
```

This is with Cold Cache 1.1 and Craft version 2.6.2989. Removing either cache tag then gives the correct content.

**Comment by mzlock** [comment]
I tried adding `key`(s) to my caches to correct this, but that doesn't seem to be fixing things and it duplicates more frequently when the entry was never enabled. There are no rows in my templatecaches table associated with the entry I'm testing.

Seems like these are conflicting when no cache is stored - so maybe `cache` and `coldcache` are using the same variable to store and render the HTML?

**Comment by mzlock** [comment]
This fix worked for me on my local version of the site immediately, but hasn't taken immediate effect on the live site. Does the plugin need a new version number or something to better trigger the change?

**Comment by angrybrad** [comment]
Just tagged release 1.1.1, which should show up in the CP as an available update.

**Comment by mzlock** [comment]
this is a bit late, but the fix here did take care of my issue 👍
