### ISSUE TITLE
Craft 3 Compatibility

### ISSUE THREAD

**Issue by rungta** [pixelandtonic/ColdCache#3]
Is the Craft 3 port complete? Don’t see it in the plugin store. Is there an ETA?

**Comment by angrybrad** [comment]
There's a v2 branch that's a Craft 3 port that hasn't been fully tested you can try if you'd like: https://github.com/pixelandtonic/ColdCache/tree/v2

On our list to verify and get it in the Plugin Store, but no ETA yet.
